#!/bin/bash
# FreeFire IPA Patcher - Ngắn gọn

unzip FreeFire.ipa -d ex
cp -R ex/Payload/FreeFire.app Payload/
rm -rf ex

install_name_tool -add_rpath @executable_path/Frameworks Payload/FreeFire.app/FreeFire
cp FreeFireHack.dylib Payload/FreeFire.app/Frameworks/

zip -r FreeFire_Patched.ipa Payload/
echo "Done! FreeFire_Patched.ipa"
